repos:
  # Conventional commit linting
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --types=feat,fix,chore
          - --body-max-line-length=250

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  # Zig formatting and linting
  - repo: local
    hooks:
      - id: zig-fmt
        name: zig fmt
        entry: zig fmt --check
        language: system
        files: \.zig$
      - id: zlint
        name: zlint
        entry: zlint
        language: system
        files: \.zig$
        pass_filenames: false
      - id: zig-test
        name: zig build test
        entry: zig build test
        language: system
        files: \.zig$
        pass_filenames: false
