name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os == 'ubuntu-latest' && 'namespace-profile-linux-amd64' || 'namespace-profile-mac-arm64' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ~/.cache/zig
            ~/AppData/Local/zig
            zig-cache
            .zig-cache
            ${{ runner.os == 'macOS' && '~/Library/Caches/hermit/pkg' || '~/.cache/hermit/pkg' }}

      - uses: cashapp/activate-hermit@v1
        with:
          cache: false

      - name: Format check
        run: zig fmt --check .

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test --summary all

      - name: Build optimized
        run: zig build -Doptimize=ReleaseFast

      - name: Run benchmarks
        run: zig build bench -Doptimize=ReleaseFast -- --format json > benchmark-results.json
        # Only run benchmarks on Linux for consistency
        if: matrix.os == 'ubuntu-latest'

      - name: Download baseline benchmark
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request'
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          branch: ${{ github.base_ref }}
          name: benchmark-results
          path: baseline
          if_no_artifact_found: warn
        continue-on-error: true

      - name: Compare benchmarks
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'pull_request'
        run: |
          if [[ -f baseline/benchmark-results.json ]]; then
            ./scripts/compare_benchmark.sh baseline/benchmark-results.json benchmark-results.json
          else
            echo "No baseline benchmark found, skipping comparison"
          fi

      - name: Upload benchmark results
        if: matrix.os == 'ubuntu-latest' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark-results.json
          retention-days: 90

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cashapp/activate-hermit@v1

      - name: Check formatting
        run: zig fmt --check .

      - name: Check for TODO/FIXME comments
        run: |
          if grep -r "TODO\|FIXME" src/ --exclude-dir=.git; then
            echo "Found TODO/FIXME comments that should be addressed or tracked as issues"
            exit 0  # Don't fail, just warn
          fi
