name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Create Manual Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cashapp/activate-hermit@v1

      - name: Run tests first
        run: zig build test

      - name: Validate version
        id: version
        run: |
          NEW_VERSION="${{ inputs.version }}"
          # Remove 'v' prefix if present
          NEW_VERSION="${NEW_VERSION#v}"

          # Basic semver validation
          if ! [[ "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format. Use X.Y.Z"
            exit 1
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version in build.zig.zon
        run: |
          NEW_VERSION="${{ steps.version.outputs.new_version }}"
          sed -i "s/\.version = \".*\"/\.version = \"$NEW_VERSION\"/" build.zig.zon

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add build.zig.zon
          git commit -m "chore: bump version to $NEW_VERSION"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.new_version }}
          name: v${{ steps.version.outputs.new_version }}
          body: |
            Manual release v${{ steps.version.outputs.new_version }}

            Created via workflow dispatch.
          draft: false
          prerelease: false
